FROM hexpm/elixir:1.18.4-erlang-28.0.2-debian-trixie-20250811-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends git inotify-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd -g $USER_GID s && \
    useradd -m -u $USER_UID -g $USER_GID s

USER s

RUN mix local.hex --force

CMD ["/bin/bash"]
